name: Deploy

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      #- run: npm ci
      #- run: npm run prod
      - run: set -eu
      - run: echo "${{ SECRETS.DEPLOY_KEY }}" > key
      - run: chmod 600 "./key"
      #- run: rsync -e "ssh -i ./key -o StrictHostKeyChecking=no"  --archive --compress --delete . ${{ SECRETS.DEPLOY_USER }}@${{ SECRETS.DEPLOY_HOST }}:${{ SECRETS.DEPLOY_PATH }}
      - run: rsync -e 'ssh -i ./deploy_key -o StrictHostKeyChecking=no' --exclude /deploy_key --exclude /.git/ --exclude /.github/ --exclude /node_modules/ \
          ./ ${{ SECRETS.DEPLOY_USER }}@${{ SECRETS.DEPLOY_HOST }}:${{ SECRETS.DEPLOY_PATH }}
